### ISSUE TITLE
typo / wrong import in digicampipe/utils/geometry.py

### ISSUE THREAD

**Issue by dneise** [calispac/digicampipe#19]
these two lines don't work:

-from ctapipe.instrument.camera import CameraGeometry
-from ctapipe.instrument.camera import _find_neighbor_pixels as find_neighbor_pixels

should be:

+from digicampipe.instrument.camera import CameraGeometry
+from digicampipe.instrument.camera import _find_neighbor_pixels as find_neighbor_pixels

in order to make it work as explained here:
[CrabAnalysis.pdf](https://github.com/calispac/digicampipe/files/1492710/CrabAnalysis.pdf)

**Comment by calispac** [comment]
This is an old version of installation procedure. see 
[package_installation_Petr_Hamal_20171121.pdf](https://github.com/calispac/digicampipe/files/1492828/package_installation_Petr_Hamal_20171121.pdf)
 Basically ctapipe should be installed from fork in calispac/ctapipe not from cocov/ctapipe anymore

We shall write a correct README for installation.

**Comment by dneise** [comment]
#21 takes up on the problem of the README. So this can be closed
