### ISSUE TITLE
libzmq.so.x dependency in protozfitsreader

### ISSUE THREAD

**Issue by calispac** [calispac/digicampipe#28]
see GH-25
lets try to keep the conversation here

**Comment by Etienne12345** [comment]
New package, that includes the libzmq depency is there:
http://www.isdc.unige.ch/~lyard/repo/ProtoZFitsReader-0.42.Python3.5.Linux.x86_64.tar.gz

Cyril, will you update the readme accordingly ? (0.41 -> 0.42)

**Comment by dneise** [comment]
perfect, please don't forget to update the `.travis.yml`accordingly

**Comment by Etienne12345** [comment]
Actually you're speaking chinese to me: I have no idea what travis is...

**Comment by Etienne12345** [comment]
Ah Ok I see: I should remove the zmq dependency from travis.yml
will do right away !

**Comment by dneise** [comment]
You said:

> Cyril, will you update the readme accordingly ? (0.41 -> 0.42)

So I assumed cyril would open a PR, with these changes to the README. I just wanted to remind him not to forget the travis.yml. 

Sorry for the confusion.

**Comment by calispac** [comment]
I ended up pushing to master.... my bad... (btw I think we should not allow to push to master, but rather open a PR from a branch). 

@Etienne12345 Travis is a bot that installs the software on a remote machine and run some scripts. If Travis build and scripts fail merging is not allowed.

**Comment by dneise** [comment]
|  I think we should not allow to push to master, but rather open a PR from a branch

totally agree, #30

**Comment by calispac** [comment]
Now admins are also restricted to the following before merging: 

1. Force push to master
2. Delete master
3. Should pass Travis checks
4. Requires review by someone else (maybe we can discard this)
