### ISSUE TITLE
README and travis installation have diverged

### ISSUE THREAD

**Issue by dneise** [calispac/digicampipe#31]
Unfortunately the README and the travis installation procedure have diverged again, so that we tell our users something different than our CI system is testing for us.

I think that should be avoided, if possible.

**Comment by Etienne12345** [comment]
Removed zmq from readme, submitted to be merged by cyril

**Comment by dneise** [comment]
Ah @Etienne12345 I think we did the same work here, I assigned myself to this issue, to communicate, that I solve it myself. I opened the issue not to complain, but to document.

**Comment by Etienne12345** [comment]
Ah... sorry, I thought that you were asking for someone to fix this. Actually I am pretty bad with git... Maybe a short tutorial to everyone working on the pipeline would be nice once the rules are clearly defined (maybe they are already following the recent talks ?)

**Comment by dneise** [comment]
I agree. If the workflow is not clear, it can quickly result in a mess. Sorry, I am so used to it, I didn't really think about it. 

Sorry.

Since I am the new guy, maybe you can tell me what the SST1M workflow is, and I simply adhere to it.
