### ISSUE TITLE
comparing ctapipe and digicampipe

### ISSUE THREAD

**Issue by dneise** [calispac/digicampipe#36]
I am currently looking into the digicampipe folder and the ctapipe folder and see some duplication in folder-names and file-names. This made me wonder if there is maybe some files in digicam-pipe that could be **imported** from ctapipe, instead of being duplicated.

At this stage, I am merely comparing files, in order to **find duplication** .. whether or not one copy can be removed from the project is another question, I think, for later.

**Comment by Etienne12345** [comment]
Afaik, a bunch of ctapipe files were duplicated into digicampipe to customize them. Maybe a very good starting point for merging would be to go through these files, and see what it would take to get rid of the digicampipe version of it ?

**Comment by dneise** [comment]
Yes.

So I went through both folders and looked for identical file names, this is the result:
```
├── ANY_pipe
│   ├── calib
│   │   ├── camera
│   │   │   ├── dl0.py
│   │   │   ├── dl1.py
│   │   │   ├── __init__.py
│   │   │   ├── r1.py
│   │   ├── __init__.py
│   ├── image
│   │   ├── __init__.py
│   ├── __init__.py
│   ├── instrument
│   │   ├── camera.py
│   │   ├── __init__.py
│   ├── io
│   │   ├── containers.py
│   │   ├── __init__.py
│   │   └── zfits.py
│   └── visualization
│       ├── __init__.py
│       ├── mpl.py
```

**Comment by dneise** [comment]
So there is not as much duplication, as I first though, both directories only overlap in 7 (14 if one also counts the mostly empty __init__.py) files (in name, content is still unclear to me at this point).

**Comment by dneise** [comment]
I am now going to compare the files, which might be duplicates by content

**Comment by dneise** [comment]
- dl0.py: look totally different.
- dl1.py: look totally different
- r1.py: look totally different
- calib.camera.__init__.py: one empty, one contains a lot of * imports
- image.__init__.py: same as above
- __init__.yp: empty - vs- contains a version
- camera.py:  
    - digicam added class CameraCalibration
    - ctapipe add a few methods here and there.
    - assumption: digicam copied from ctapipe, but not from the version I am looking at.
- instrument.__init__.py: empty - vs- some imports
- containers.py: not utterly different but clearly diverged
- zfits.py: both implement `zfits_event_source()` but diff is large.
- mpl.py: nearly identical.

**Comment by dneise** [comment]
> Maybe a very good starting point for merging would be to go through these files, and see what it would take to get rid of the digicampipe version of it ?

@Etienne12345  I totally agree. Just I have no idea how an where to start.

I would now start implementing a lot of tests, to fix (at least) some basic functionality of digicampipe, then I could start to tidy it up, without the fear to miss something or break something as long as the tests pass.

But as I just started here, I have no idea, what digicampipe is supposed to do. I think, I cannot provide theses tests based on my current knowledge.

Also some test input might be helpful.

**Comment by dneise** [comment]
See also #27

**Comment by dneise** [comment]
Does anybody know, if there is suitable test input in https://github.com/cta-observatory/ctapipe-extra ??

**Comment by calispac** [comment]
I think this is an important discussion to have next week face-to-face or at out next call !
Personally, I am for using the ctapipe framework.

**Comment by dneise** [comment]
I think this issue is dead.
