### ISSUE TITLE
Follow PEP8 ?

### ISSUE THREAD

**Issue by dneise** [calispac/digicampipe#38]
Not everybody has a very wide screen. We have seen it today, when looking at code on the projector. Many lines were to long to look at them and think about them.

This is one of the reasons, why PEP8 proposes to stop at column ~80.

Another good reason is that, even if you have a wide screen, you might wanna compare two files ... 
this is easier when both files are nicely narrow.

Also if you want to edit code, and try it out in a ipython-notebook .. and so on and so on.

https://www.python.org/dev/peps/pep-0008/#maximum-line-length

I propose to adhere to PEP8 regarding line length in all new PRs.

**Comment by calispac** [comment]
Yes let's stick to PEP8 since it is also adopted by other python projects in CTA. Btw PyCharm can check code styling.

**Comment by calispac** [comment]
PEP8 checking is integrated to each pull request.
