### ISSUE TITLE
possible issue with `io/protozfitsreader.py`

### ISSUE THREAD

**Issue by dneise** [calispac/digicampipe#44]
Hello, have a question about a line in `io.protozfitsreader.py`. 

https://github.com/calispac/digicampipe/blob/b5e17ddd6e402710dfdb978c278742ed35f2623c/digicampipe/io/protozfitsreader.py#L324-L330

This question is about line 328, but I am not quite sure I understand the inputs `pixels`, `baselines`.
I assume:
 - `pixels`: a 1D array of (integer) pixel ids, no necessarily ordered, but no duplicates
 - `baselines`: a 1D array of floats, having the same length as `pixels`.

Are these assumptions correct? That is my first question.

-----

Now, first I assumed `pixels` is a **sorted** list of all pixel ids, and thus I did not understand why line 328 is needed at all, since *if pixels is sorted and has no duplicates* then *properties is identical with baselines*.

So I thought: "Ahaaa properties is a sorted version of baselines" :-D
But wait! This is using an implementation detail of dicts, in the C-implementation of python.
(Also it is slow)

Let me show you this is a problem:

I prepared a little test script: `properties.py` with this contents:
```python
import numpy as np

np.random.seed(0)
n_pixels = 5
pixels = np.arange(n_pixels)
np.random.shuffle(pixels)
baselines = pixels + 0.1

print('pixels:', pixels)
print('baselines:', baselines)

properties = np.array(list(dict(zip(pixels, baselines)).values()))
print('properties', properties)
```

I set the random seed, so it executes the same on all our machines:
This is the output one would expect, right?
```
pixels: [2 0 1 3 4]
baselines: [ 2.1  0.1  1.1  3.1  4.1]
properties [ 0.1  1.1  2.1  3.1  4.1]
```

pixels is some list of indices, not sorted, but no duplicates,  baselines is just some floats, but I made them, so we can see which baseline belongs to which pixel. properties now, is a sorted version of baseline. Keep in mind it is not sorted by size, it is sorted according to the order of `pixels`.

Now let me show you how it looks in a py3.5 and a py3.6 environment.

### python 3.5
```
(foo) dneise@lair:~/ctasoft/digicampipe/digicampipe/io$ ipython
Python 3.5.4 |Anaconda, Inc.| (default, Nov 20 2017, 18:44:38) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %run properties.py
pixels: [2 0 1 3 4]
baselines: [ 2.1  0.1  1.1  3.1  4.1]
properties [ 0.1  1.1  2.1  3.1  4.1]
```

It works nicely.

### python 3.6
```
dneise@lair:~$ ipython
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %run properties.py
pixels: [2 0 1 3 4]
baselines: [ 2.1  0.1  1.1  3.1  4.1]
properties [ 2.1  0.1  1.1  3.1  4.1]
```

What? it does not work at all? 
Correct, it is a mistake to rely on the ordering of keys or values inside a `dict`.
The sorting worked just by chance. 

----

So given, that I am not sure about the authors intention, let me ask:

What should `properties` be? A sorted version of `baselines` Or does the order not matter at all?

If it should be ordered I propose this solution: `properties = baselines[np.argsort(pixels)]`

### executed in a py3.5 environment:
```
(foo) dneise@lair:~$ ipython propoerties.py 
pixels: [2 0 1 3 4]
baselines: [ 2.1  0.1  1.1  3.1  4.1]
timeing: properties = np.array(list(dict(zip(pixels, baselines)).values()))
3.15 µs ± 25.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
properties [ 0.1  1.1  2.1  3.1  4.1]

timeing: properties2 = baselines[np.argsort(pixels)]
1.53 µs ± 9.56 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
properties2 [ 0.1  1.1  2.1  3.1  4.1]
```

You see it is ~2 times faster for `n_pixels = 5`, for more realistic pixel numbers like 
`n_pixels = 1296` one gets

```
(foo) dneise@lair:~$ ipython propoerties.py 
pixels: [ 936  474 1028 ..., 1216  559  684]
baselines: [  936.1   474.1  1028.1 ...,  1216.1   559.1   684.1]
timeing: properties = np.array(list(dict(zip(pixels, baselines)).values()))
304 µs ± 3.24 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
properties [  1.00000000e-01   1.10000000e+00   2.10000000e+00 ...,   1.29310000e+03
   1.29410000e+03   1.29510000e+03]

timeing: properties2 = baselines[np.argsort(pixels)]
35.6 µs ± 109 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
properties2 [  1.00000000e-01   1.10000000e+00   2.10000000e+00 ...,   1.29310000e+03
   1.29410000e+03   1.29510000e+03]
```

This is roughly a factor of 8.5 faster.

**Comment by Etienne12345** [comment]
Yes !  Now I remember: it was exactly this: the dictionaries did not behave "as expected" under python 3.6. As you pointed out, I am not sure what we should expect at all actually (Did not write the wrapper code myself).

**Comment by dneise** [comment]
I read a bit more through the code and become more and more sure that `get_baseline` is intended to return the baseline sorted according to the pixel_ids. 

I am currently re-working that file `io.protozfitsreader.py` a bit. I'll open a PR asap, so interested people can have a look at it.

**Comment by calispac** [comment]
@dneise 

> baselines: a 1D array of floats, having the same length as pixels.

baselines : a 1D array of UINT12, changed to UINT16 (it is the baseline computed by DigiCam from 1024*4 ns before the threshold has passed (maybe shifted by a few samples.)).

The arrays are not initially sorted so we need to reorder them at this stage. 

> What should properties be? A sorted version of baselines Or does the order not matter at all?

Yes the order matters. The first solution was to have each Field in the Container beeing a dict where the keys represent the pixel id. But I the end I changed it such that you access : 

`baseline_pixel_zero = baselines[0]`
instead of
`baseline_pixel_zero = baselines['0']`
Using arrays instead of dict make it easier for the numpy array operations.

> If it should be ordered I propose this solution: properties = baselines[np.argsort(pixels)]

I like this solution much more. Can we store `np.argsort(pixels)` at the first event of each file such that we don't need to do the sorting at each event ? Or pixel ordering can change with event number @Etienne12345 ?

P.S. Of course we can repeat this for the other fields as well.

**Comment by dneise** [comment]
Thanks @calispac for the clarification, just one question again:

what is `pixels`. I assume it is a shuffled list of integers, which contains all numbers from 0 ... N_pixels-1. 
It does not have any duplicates and it does not have any holes, is that correct?

**Comment by calispac** [comment]
>  It does not have any duplicates and it does not have any holes, is that correct?
It is correct. 
However it is not true for patch_id. 
Patches have duplicates in the neighborhood of sectors (so does the trigger inputs/ouputs). In the end  the duplicates are removed.

**Comment by dneise** [comment]
okay we need more tests for this .. .do we already have test files?

**Comment by dneise** [comment]
This was just solved I think
