### ISSUE TITLE
cannot execute `pipeline_crab` on crab events

### ISSUE THREAD

**Issue by dneise** [calispac/digicampipe#73]
Today I finally found time to download the crab files using Etienne's script.
The files are named: 
```
SST1M01_20171030.000.fits.fz
....
SST1M01_20171030.091.fits.fz
DigicamSlowControl_20171030_004.fits
DigicamSlowControl_20171030_007.fits
DigicamSlowControl_20171030_009.fits
DriveSystem_20171030_001.fits
DriveSystem_20171030_003.fits
SafetyPLC_20171030_000.fits
SafetyPLC_20171030_005.fits
```

I call the script like this:
```
(digicampipe) dneise@lair:~/ctasoft/digicampipe$ python pipeline_crab.py \
    -p /home/dneise/ctasoft/sst1m_crab/ \
    -o /home/dneise/ctasoft/sst1m_crab/out/
```

And get this error:
```
Traceback (most recent call last):
  File "pipeline_crab.py", line 36, in <module>
    dark_baseline = np.load(directory + 'dark.npz')
  File "/home/dneise/anaconda3/envs/digicampipe/lib/python3.5/site-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/dneise/ctasoft/sst1m_crab/dark.npz'
```

**Comment by dneise** [comment]
So obviously I am missing a file called "dark.npz". Should I have downloaded this file? 
Can I generate this file somehow?

And is there already some docu about this, which I simply should read? :-D

**Comment by calispac** [comment]
this file is supposed to be generated with : https://github.com/calispac/digicampipe/blob/master/dark_evaluation.py

It basically reads the data taken with the lid closed compute the baseline and creates this .npz to store it. This baseline (in dark condition) is used to compute the baseline shift, used for : 
- nsb computation
- gain drop computation

Here I see two issues at the moment : 

1.  There is no way to know if an event is taken with lid closed or opened (at least to my knowledge) from the .zfits or the slow control data. (only from the logbook)
2. As you experienced it is not documented how to generate this file. It was proposed to add this computation step into the crab_pipeline.py

**Comment by Etienne12345** [comment]
One can retrieve the status of the lid from the slow control data. I am actually doing it with the metadata that is extracted "per raw data file". Should I send an email to Yves to ask him to add that to the pipeline ? I can explain him where the value should be retrieved from.

**Comment by dneise** [comment]
> Should I send an email to Yves to ask him to add that to the pipeline ?

What is meant by "the pipeline" here?

**Comment by Etienne12345** [comment]
Digicampipe / pipeline_crab.py

**Comment by dneise** [comment]
I tried to execute `dark_evaluation.py` but I cannot get it to work. 
Of course I had to modify it a bit. But even after that, I cannot get it to work. I will open a dedicated issue for that.

**Comment by dneise** [comment]
I think if something is missing in `pipeline_crab.py` then an issue should be opened. And technical details should be exchanged there ... so other people can also learn that. Emails ... tend to be somehow ... well .. kinda ... private ...
