### ISSUE TITLE
Partly Filled Containers?

### ISSUE THREAD

**Issue by dneise** [calispac/digicampipe#78]
#75 brought my attention to the fact, that we fill this Container:
https://github.com/calispac/digicampipe/blob/39ab15dcd16179489ecf172db17ce73d58dce768/digicampipe/io/containers.py#L80-L126

In different places of the code, and it can even happen, that some parts of the container are not filled, c.f. "expert_mode". 

I as a user felt totally helpless in that situation. I had never in my live expected a Container to be filled in different parts of the code, which might even be left out sometimes.

The reason for doing this, is (I think) clear to me: 
Performance. 
If everything we wanted to fill into the R0 container would happen in zero-time, we would of course always fill it completely.

So ... now the question is: 
Can we give users in my situation a hint?

**Comment by dneise** [comment]
Also I have to check how ctapipe is doing that. They might have an answer already.

**Comment by calispac** [comment]
As we are in a code+telescope+camera prototyping phase I would prefer that we seperate as much as possible all the computation steps. For instance, one could do for charge reconstruction : 

```python
def reco_charge(data):
     baseline = np.mean(data.waveform)
     data.baseline = baseline
     data.charge = np.max(data.waveform - baseline)
     return data
```

Then in the future you realize that doing this baseline computation turn out to be useful for an other step of the pipeline. 

So you end up doing 

```python
def compute_baseline(data):
     data.baseline = np.mean(data.waveform)
     return data
def compute_charge(data):
     data.charge = np.max(data.waveform - baseline)
```
So I prefer to have 1 function for 1 application. Then of course the user is completely free of doing something wrong he can for instance call `compute_charge()` then `compute_baseline()` which would result in an ugly error. However it is more flexible for a development phase. For instance one could have : 

```python
def compute_baseline_1(data):
det compute_baseline_2(data):
.
.
.
def compute_charge_1(data):
def compute_charge_2(data):
.
.
.
```

With this you can play with the various algorithm and find which one suits best your use case.

**Comment by dneise** [comment]
Ah .. I see.

Yes small functions are certainly good!

My point is: We have hierarchial container, with keys like this:
```
data.r0.event_id
data.r0.tels_with_data
data.inst.num_channels[tel_id]
data.r0.tel[tel_id].camera_event_number
data.r0.tel[tel_id].adc_samples
```

The hierarchy here reflects the design of CTA somehow. 
It does not reflect the design of the software. 
As a consequence I do not know which function is supposed to fill e.g. this field: `r0.tels_with_data`

I do also not know, if a field is not filled, whether this is a bug, or if this field is intentionally left empty. 

I think, this can be a problem. But maybe ... right now, we cannot do anything about it, since being flexible is much more important.

**Comment by dneise** [comment]
This was more of a question, not a task ... I guess I should close it
