### ISSUE TITLE
Camera - config_file and geometry

### ISSUE THREAD

**Issue by dneise** [calispac/digicampipe#80]
In many places I see code like this:
```python
camera_config_file = pkg_resources.resource_filename(
        'digicampipe',
        path.join(
            'tests',
            'resources',
            'camera_config.cfg'
        )
    )
digicam = Camera(_config_file=camera_config_file)
digicam_geometry = geometry.generate_geometry_from_camera(camera=digicam)
```

And later I see functions, which need both `camera` and `camera_geometry` as parameters.

What if we would make a little utility class like this? maybe in `ctapipe.utils`.
```python
import pkg_resources
from os import path

from cts_core import camera
from digicampipe.utils import geometry


class Camera(camera.Camera):
    def __init__(self, *args, **kwargs):
        if not args and kwargs.get('_config_file', None) is None:
            kwargs['_config_file'] = pkg_resources.resource_filename(
                'digicampipe',
                path.join(
                    'tests',
                    'resources',
                    'camera_config.cfg'
                )
            )
        super().__init__(*args, **kwargs)

        self.geometry = geometry.generate_geometry_from_camera(camera=self)
```

This little helper class has two advantages, without touching the code in CTS.
 1. if no `_config_file` is given, it just falls back to the `camera_config.cfg` which is provided with digicampipe.
 2. It has an *additional* attribute `.geometry`.

So we can now slowly start porting functions which at the moment have this interface:
```python
def some_function(camera, camera_geometry):
    # do something with camera and camera_geometry
```

to this interface:
```python
import warnings

def some_function(camera, camera_geometry=None):
     if camera_geometry is None:
         camera_geometry = camera.geometry
    else:
        warnings.warn("camera_geometry is deprecated. Use utils.Camera instead", DeprecationWarning)
    # do something with camera and camera_geometry
    # this code does not even realize that something was changed above it.
```

And then at some point when we assume every part of the code was ported to the new interface:
```python
def some_function(camera):
         camera_geometry = camera.geometry
    # do something with camera and camera_geometry
    # this code does not even realize that something was changed above it.
```
This will throw an exception in the users face, but they had enough time to port....

**Comment by calispac** [comment]
Having `Camera` and `CameraGeometry` is confusing I agree. This was implemented so because of the lack of a "complete" `Camera` object inside `ctapipe`. But as a temporary solution I think what you propose is fine. In my opinion such object should exist in `ctapipe`.

I also think that the `cts.Camera` object has no much need to be in CTS. As this software is supposed to be stand alone for controlling the calibration setup. As this part of CTS is actually also useful for `digicampipe` and `digicamviewer`, what do you think on moving it in a stand alone package ?
